<?php

/**
 * ProcessWire Template Twig Replace Language Support
 *
 * See README.md for usage instructions.
 *
 * ProcessWire 2.x
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 *
 * @author Tabea David <td@kf-interactive.com>
 * @version 0.0.1
 * @copyright Copyright (c) 2014 KF Interactive, www.kf-interactive.com, <info@kf-interactive.com>
 * @see https://github.com/justonestep/processwire-processlanguagetranslatortwigsupport
 * @see http://www.processwire.com
 */

/**
 * Class TemplateTwigReplaceLanguageSupport
 */
class TemplateTwigReplaceLanguageSupport extends WireData implements Module {

  /**
   * Retrieves module meta data
   * Implementation of the Module interface
   *
   * @return array
   * @see http://processwire.com/apigen/class-Module.html
   */
  public static function getModuleInfo() {

    return array(
      'title' => 'Template Twig Replace Language Support',
      'version' => 001,
      'summary' => 'Multi-language support for Twig template engine',
      'href' => 'https://github.com/justonestep/processwire-processlanguagetranslatortwigsupport',
      'singular' => true,
      'autoload' => true,
      'requires' => 'TemplateTwigReplace'
    );
  }

  /**
   * Extends the twig render engine
   *
   */
  public function init() {
    // retrieve the Twig_Environment instance
    $this->twig = wire('modules')->get('TemplateTwigReplace')->getTwig();

    // new twig function to enable translations
    // @see: http://processwire.com/api/multi-language-support/code-i18n/
    $function = new Twig_SimpleFunction("__", function ($text, $filename = '', $context = '') {
      if (!empty($filename)) {
        if ($this->twig->getLoader()->exists($filename . '.twig')) {
          $textdomain = $this->twig->getLoader()->getCacheKey($filename . '.twig');
          $language = $this->user->language;
          $out = htmlspecialchars($language->translator()->getTranslation($textdomain, $text, $context), ENT_QUOTES, 'UTF-8');
        } else {
          $out = $text;
        }

        return $out;
      }
    });

    // add function to twig environment
    $this->twig->addFunction($function);
  }
}
